site_name: datar
repo_url: https://github.com/pwwang/datar
repo_name: pwwang/datar
theme:
    favicon: favicon.png
    logo: favicon.png
    icon:
        repo: fontawesome/brands/github
    palette:
        primary: black
    name: 'material'
    font:
      text:
        - FreightSans
        - "Helvetica Neue"
        - Helvetica
        - Arial
        - sans-serif
      code:
        - IBMPlexMono
        - SFMono-Regular
        - Menlo
        - Monaco
        - Consolas
        - "Liberation Mono"
        - "Courier New"
        - monospace
    features:
        - navigation.top
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
    - mkdocs-jupyter:
        execute: false
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Reference maps':
        'ALL': 'reference-maps/ALL.md'
        'base': 'reference-maps/base.md'
        'dplyr': 'reference-maps/dplyr.md'
        'tibble': 'reference-maps/tibble.md'
        'tidyr': 'reference-maps/tidyr.md'
        'forcats': 'reference-maps/forcats.md'
        'data': 'reference-maps/datasets.md'
        'other': 'reference-maps/other.md'
    - 'Import datar': 'import.md'
    - 'Backends': 'backends.md'
    - 'Options': 'options.md'
    - 'The f-expression': 'f.md'
    - 'Data': 'data.md'
    - 'Examples':
        'across': 'notebooks/across.ipynb'
        'add_column': 'notebooks/add_column.ipynb'
        'add_row': 'notebooks/add_row.ipynb'
        'arrange': 'notebooks/arrange.ipynb'
        'base': 'notebooks/base.ipynb'
        'base-arithmetic': 'notebooks/base-arithmetic.ipynb'
        'base-funs': 'notebooks/base-funs.ipynb'
        'between': 'notebooks/between.ipynb'
        'bind': 'notebooks/bind.ipynb'
        'case_when': 'notebooks/case_when.ipynb'
        'chop': 'notebooks/chop.ipynb'
        'coalesce': 'notebooks/coalesce.ipynb'
        'complete': 'notebooks/complete.ipynb'
        'context': 'notebooks/context.ipynb'
        'count': 'notebooks/count.ipynb'
        'cumall': 'notebooks/cumall.ipynb'
        'desc': 'notebooks/desc.ipynb'
        'distinct': 'notebooks/distinct.ipynb'
        'drop_na': 'notebooks/drop_na.ipynb'
        'enframe': 'notebooks/enframe.ipynb'
        'expand': 'notebooks/expand.ipynb'
        'expand_grid': 'notebooks/expand_grid.ipynb'
        'extract': 'notebooks/extract.ipynb'
        'fill': 'notebooks/fill.ipynb'
        'filter': 'notebooks/filter.ipynb'
        'filter-joins': 'notebooks/filter-joins.ipynb'
        'forcats_fct_multi': 'notebooks/forcats_fct_multi.ipynb'
        'forcats_lvl_addrm': 'notebooks/forcats_lvl_addrm.ipynb'
        'forcats_lvl_order': 'notebooks/forcats_lvl_order.ipynb'
        'forcats_lvl_value': 'notebooks/forcats_lvl_value.ipynb'
        'forcats_misc': 'notebooks/forcats_misc.ipynb'
        'full_seq': 'notebooks/full_seq.ipynb'
        'other': 'notebooks/other.ipynb'
        'group_by': 'notebooks/group_by.ipynb'
        'group_map': 'notebooks/group_map.ipynb'
        'group_split': 'notebooks/group_split.ipynb'
        'group_trim': 'notebooks/group_trim.ipynb'
        'lead-lag': 'notebooks/lead-lag.ipynb'
        'mutate-joins': 'notebooks/mutate-joins.ipynb'
        'mutate': 'notebooks/mutate.ipynb'
        'n_distinct': 'notebooks/n_distinct.ipynb'
        'na_if': 'notebooks/na_if.ipynb'
        'near': 'notebooks/near.ipynb'
        'nest': 'notebooks/nest.ipynb'
        'nest-join': 'notebooks/nest-join.ipynb'
        'nth': 'notebooks/nth.ipynb'
        'pack': 'notebooks/pack.ipynb'
        'pivot_longer': 'notebooks/pivot_longer.ipynb'
        'pivot_wider': 'notebooks/pivot_wider.ipynb'
        'pull': 'notebooks/pull.ipynb'
        'ranking': 'notebooks/ranking.ipynb'
        'readme': 'notebooks/readme.ipynb'
        'recode': 'notebooks/recode.ipynb'
        'relocate': 'notebooks/relocate.ipynb'
        'rename': 'notebooks/rename.ipynb'
        'replace_na': 'notebooks/replace_na.ipynb'
        'rownames': 'notebooks/rownames.ipynb'
        'rows': 'notebooks/rows.ipynb'
        'rowwise': 'notebooks/rowwise.ipynb'
        'select': 'notebooks/select.ipynb'
        'separate': 'notebooks/separate.ipynb'
        'setops': 'notebooks/setops.ipynb'
        'slice': 'notebooks/slice.ipynb'
        'summarise': 'notebooks/summarise.ipynb'
        'tibble': 'notebooks/tibble.ipynb'
        'uncount': 'notebooks/uncount.ipynb'
        'unite': 'notebooks/unite.ipynb'
        'with_groups': 'notebooks/with_groups.ipynb'
    - 'API': 'mkapi/api/datar'
    - 'Change Log': CHANGELOG.md
