
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='datar',
    version='0.0.3',
    description='Port of R data packages tidyr, dplyr, tibble and so on in python',
    python_requires='==3.*,>=3.7.1',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    packages=['datar', 'datar.base', 'datar.core', 'datar.datar', 'datar.datasets',
              'datar.dplyr', 'datar.stats', 'datar.tibble', 'datar.tidyr', 'datar.utils'],
    package_dir={"": "."},
    package_data={"datar.datasets": ["*.gz"]},
    install_requires=['modkit', 'pandas==1.*,>=1.2.0', 'pipda'],
    extras_require={"dev": ["pytest", "pytest-cov"]},
)
