
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='plyrda',
    version='0.0.3',
    description='Probably the closest port of tidyr + dplyr in python',
    python_requires='==3.*,>=3.7.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    packages=['plyrda', 'plyrda.data'],
    package_dir={"": "."},
    package_data={"plyrda.data": ["*.gz"]},
    install_requires=['modkit', 'pandas==1.*,>=1.1.4', 'pipda'],
    extras_require={"dev": ["pytest", "pytest-cov"]},
)
