name: Bug Report
description: Report incorrect behavior in the datar library
title: "[BUG] "
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: datar version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            **latest version** of datar and its backends.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: >
        Please paste the output of ``datar.get_versions()``
      value: >
        <details>


        Replace this line with the output of datar.get_versions()


        </details>
    validations:
      required: true
